In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
arr = np.arange(1,20, 2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [9]:
arr = np.linspace(0, 100, 5)
arr

array([  0.,  25.,  50.,  75., 100.])

In [10]:
ones = np.ones(4)
ones

array([1., 1., 1., 1.])

In [14]:
empt_arr = np.empty(3)

rand_arr = np.random.rand(12)
rand_arr

array([0.43523618, 0.53059859, 0.05087507, 0.41245967, 0.64606661,
       0.59086442, 0.56927173, 0.55933995, 0.07257239, 0.90810184,
       0.38385634, 0.21079721])

In [42]:
arr_mul = np.array([[12,3,4], [6,7,4], [6,7,5]]).reshape(-1,1)
arr_mul[::-1]

array([[ 5],
       [ 7],
       [ 6],
       [ 4],
       [ 7],
       [ 6],
       [ 4],
       [ 3],
       [12]])

In [48]:
a1 = np.array([[1,1], 
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])

np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [51]:
arr_4 =np.array([1, 2, 3, 4], dtype=float)
arr_4

array([1., 2., 3., 4.])

In [59]:
arr = np.array([1, 2 ,3 ,4 ,5 ,6, 7,8,]).reshape((2, -1))
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [60]:
arr_1 = np.array([1,2,4])
arr_2 = np.array([4,5,4])

new_arr = np.append([12,3,4], arr_1, arr_2)
new_arr

TypeError: only integer scalar arrays can be converted to a scalar index